//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Event
{
    public Event()
    {
        this.Logs = new HashSet<Log>();
    }

    public int eventID { get; set; }
    public string eventName { get; set; }
    public System.DateTime startDate { get; set; }
    public System.DateTime endDate { get; set; }
    public int addressID { get; set; }

    public virtual ICollection<Log> Logs { get; set; }
    public virtual Address Address { get; set; }
}
