//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Organization
{
    public Organization()
    {
        this.Logs = new HashSet<Log>();
    }

    public int OrgID { get; set; }
    public string OrgName { get; set; }

    public virtual ICollection<Log> Logs { get; set; }
}
