//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteer_Iowa_Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string lineOne { get; set; }
        public string lineTwo { get; set; }
        public string zip { get; set; }
        public int cityID { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual City City { get; set; }
    }
}
