//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteer_Iowa_Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int logID { get; set; }
        public int hoursLogged { get; set; }
        public int userId { get; set; }
        public int orgID { get; set; }
        public int eventID { get; set; }
    
        public virtual Users UserProfile { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Event Event { get; set; }
    }
}
